BasedOnStyle: Google
AccessModifierOffset: -2
AlignAfterOpenBracket: Align
AlignArrayOfStructures: None # Left/right buggy v16
AlignConsecutiveAssignments: # Consecutive # Custom fields v16
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignConsecutiveBitFields: # Consecutive # Custom fields v16
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignConsecutiveDeclarations: # Consecutive # Custom fields v16
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignConsecutiveMacros: # Consecutive # Custom fields v16
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignEscapedNewlines: Left
AlignOperands: Align
# AlignTrailingComments: true # < v16
AlignTrailingComments: # >= v16
  Kind: Always
  OverEmptyLines: 0

AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: false

AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: Yes

BinPackArguments: true
BinPackParameters: true

BitFieldColonSpacing: After
BraceWrapping:
  AfterCaseLabel:	true
  AfterClass:	true
  AfterControlStatement: Always
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: true
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
# BracedInitializerIndentWidth: 0 # v17

BreakAfterAttributes: Never # v16
BreakAfterJavaFieldAnnotations: true
BreakArrays: false # v16
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BreakBeforeConceptDeclarations: Allowed
BreakBeforeInlineASMColon: OnlyMultiline # v16
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeColon
BreakInheritanceList: AfterComma
BreakStringLiterals: true

ColumnLimit: 80
CompactNamespaces: false

ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 4

Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat: false

EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: Always

FixNamespaceComments: true

# ForEachMacros: ['RANGES_FOR', 'FOREACH']
# IfMacros: ['IF']
IncludeBlocks: Regroup
IncludeCategories:
# Note : don't change the order
# Libraries
  - Regex:           '<.*\/.*>'
    Priority:        3
# STD includes
  - Regex:           '<.*>'
    Priority:        2
# Project Files
  - Regex:           '".*\/.*"'
    Priority:        4
# Header
  - Regex:           '".*"'
    Priority:        1

IndentAccessModifiers: false
IndentCaseBlocks: true
IndentCaseLabels: false
IndentExternBlock: AfterExternBlock
IndentGotoLabels: false
IndentPPDirectives: AfterHash
IndentRequires: true
IndentRequiresClause: true
IndentWidth: 4
IndentWrappedFunctionNames: true

InsertBraces: true
InsertNewlineAtEOF: true # v16
InsertTrailingCommas: None # Cannot use that if BinPackArguments is set to true
IntegerLiteralSeparator: # v16
  Binary: 4
  Decimal: 3
  Hex: 2
#   BinaryMinDigits: 4 # (doesn't work)
#   DecimalMinDigits: 3 # (doesn't work)
#   HexMinDigits: 2 # (doesn't work)

# JavaImportGroups: ['com.example', 'com', 'org'] # Don't know what to put
JavaScriptQuotes: Single
JavaScriptWrapImports: true

KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature

Language: Cpp
LineEnding: LF # v16

MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
PPIndentWidth: 4

PackConstructorInitializers: NextLine

PenaltyBreakAssignment: 100
PenaltyBreakBeforeFirstCallParameter: 50
PenaltyBreakComment: 1000
PenaltyBreakFirstLessLess: 200
PenaltyBreakOpenParenthesis: 114
PenaltyBreakString: 10
PenaltyBreakTemplateDeclaration: 0
PenaltyExcessCharacter: 2000
PenaltyIndentedWhitespace: 0
PenaltyReturnTypeOnItsOwnLine: 300

PointerAlignment: Middle
QualifierAlignment: Custom # v16
QualifierOrder: ['constexpr', 'inline', 'volatile', 'static', 'type', 'const' ] # v16
# RawStringFormats # Don't know what to put
ReferenceAlignment: Middle

ReflowComments: true
# RemoveBracesLLVM: false # Useless
RemoveSemicolon: true # v16

RequiresClausePosition: WithPreceding
RequiresExpressionIndentation: Keyword # v16

SeparateDefinitionBlocks: Always
ShortNamespaceLines: 0

SortIncludes: CaseSensitive
SortJavaStaticImport: Before
SortUsingDeclarations: true

SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: true
SpaceAfterTemplateKeyword: false
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
# SpaceBeforeJsonColon: false # v17
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterFunctionDeclarationName: true
  AfterFunctionDefinitionName: true
  AfterIfMacros: true
  AfterOverloadedOperator: true
  AfterRequiresInClause: true # clang 15
  AfterRequiresInExpression: true # clang 15
  BeforeNonEmptyParentheses: false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 2
SpacesInAngles: Always # clang 13
SpacesInCStyleCastParentheses: true
SpacesInConditionalStatement: true
SpacesInContainerLiterals: true
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
SpacesInParentheses: true
SpacesInSquareBrackets: false

Standard: Latest
UseTab: Never